In [1]:
import cv2

C:\anaconda_new\lib\site-packages\numpy\core\__init__.py:29: UserWarning: loaded more than 1 DLL from .libs:
C:\anaconda_new\lib\site-packages\numpy\.libs\libopenblas.IPBC74C7KURV7CB2PKT5Z5FNR3SIBV4J.gfortran-win_amd64.dll
C:\anaconda_new\lib\site-packages\numpy\.libs\libopenblas.TXA6YQSD3GCQQC22GEQ54J2UDCXDXHWN.gfortran-win_amd64.dll
  stacklevel=1)


In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
im_1=cv2.imread("C:/Users/admin pc/Desktop/lena_256.jpg",0)

In [4]:
im_1

array([[139, 134, 133, ..., 144, 150, 123],
       [138, 135, 133, ..., 151, 156, 127],
       [135, 135, 133, ..., 118, 106,  78],
       ...,
       [ 25,  26,  27, ...,  54,  62,  63],
       [ 21,  24,  27, ...,  61,  67,  66],
       [ 20,  25,  28, ...,  69,  72,  70]], dtype=uint8)

In [5]:
im_1.shape

(256, 256)

In [6]:
cv2.imshow('im_1',im_1)

In [7]:
#cv2.waitKey(0)

In [8]:
from skimage.transform import resize
im_3=resize(im_1,(100,100))

In [9]:
im_3.shape

(100, 100)

In [10]:
im_3

array([[0.52635294, 0.52186196, 0.51773333, ..., 0.33058039, 0.40764863,
        0.52348392],
       [0.51602039, 0.50676235, 0.50886275, ..., 0.35846275, 0.28641569,
        0.1562698 ],
       [0.50618824, 0.50329412, 0.50592157, ..., 0.26639216, 0.11265098,
        0.08282353],
       ...,
       [0.11952941, 0.1398902 , 0.20937255, ..., 0.1247451 , 0.10974902,
        0.09577255],
       [0.10109804, 0.11425725, 0.17210196, ..., 0.10567059, 0.12706824,
        0.17443137],
       [0.09171922, 0.10329412, 0.13200784, ..., 0.10534902, 0.19202039,
        0.25424157]])

In [11]:
cv2.imshow('im_3',im_3)

In [12]:
#cv2.waitKey(0)

In [13]:
im_2=im_3.flatten()

In [14]:
im_2

array([0.52635294, 0.52186196, 0.51773333, ..., 0.10534902, 0.19202039,
       0.25424157])

In [15]:
data=list(im_2)

In [16]:
data

[0.5263529411764705,
 0.5218619607843138,
 0.5177333333333333,
 0.5141223529411765,
 0.5020564705882354,
 0.4961270588235293,
 0.5026305882352943,
 0.5318901960784319,
 0.5677647058823533,
 0.580390588235294,
 0.543450980392156,
 0.4432423529411754,
 0.28670588235294,
 0.24020862745098076,
 0.27239215686274526,
 0.2837647058823531,
 0.28917647058823537,
 0.28988235294117637,
 0.29105882352941176,
 0.291185882352941,
 0.2978211764705885,
 0.32227921568627466,
 0.3431294117647061,
 0.35811764705882365,
 0.3635623529411767,
 0.3805819607843137,
 0.3852549019607845,
 0.388713725490196,
 0.37827450980392163,
 0.38431372549019605,
 0.38580392156862753,
 0.38560470588235296,
 0.39333333333333326,
 0.3921568627450981,
 0.3921568627450981,
 0.3903388235294117,
 0.395607843137255,
 0.3941176470588236,
 0.39712470588235294,
 0.4,
 0.4001552941176471,
 0.3941960784313725,
 0.38217254901960784,
 0.38125490196078426,
 0.3977254901960785,
 0.3853160784313724,
 0.3829066666666666,
 0.396078431372549,


In [17]:
import random

In [18]:
k1=random.choice(data)

In [19]:
k1

0.10333803921568609

In [20]:
k2=random.choice(data)

In [21]:
k2

0.2394274509803922

In [22]:
import statistics

In [23]:
k011=0
k022=0
while k1!=k011 and k2!=k022:
    s1111=[]
    s2222=[]
    for i in data:
        y1=(i-k1)**2
        y2=(i-k2)**2
        s1111.append((y1,i))
        s2222.append((y2,i))
        #print(s2222)
    s000=[]
    for (a,b) in s1111:
        for (c,d) in s2222:
            if b==d:
                y=(a,c,b)
                s000.append(y)
    #print(s000)
    s11_11=[]
    s22_22=[]
    for (a,c,b) in s000:
        e=min(a,c)
        if e==a:
            s11_11.append(b)
        elif e==c:
            s22_22.append(b)
        else:
            pass
    #print(s22_22)
    s333=[]
    s444=[]
    k011=statistics.median(s11_11)
    k022=statistics.median(s22_22)
    k001=round(k011,3)
    k002=round(k022,3)
    p1=(s11_11,k001)
    p2=(s22_22,k002)
    s333.append(p1)
    s444.append(p2)
    #print(k002)
    if k1==k001 and k2==k002:
        print(k1,k2)
        print(s333,s444)
        break
    else:
        k1=k001  
        k2=k002
            
#print ( k1 , k2)

0.244 0.522
[([0.28670588235294, 0.24020862745098076, 0.27239215686274526, 0.2837647058823531, 0.28917647058823537, 0.28988235294117637, 0.29105882352941176, 0.291185882352941, 0.2978211764705885, 0.32227921568627466, 0.3431294117647061, 0.35811764705882365, 0.3635623529411767, 0.3805819607843137, 0.37827450980392163, 0.38217254901960784, 0.38125490196078426, 0.3829066666666666, 0.3803921568627451, 0.3803921568627451, 0.3803921568627451, 0.3803921568627451, 0.3803921568627451, 0.3803921568627451, 0.3785882352941176, 0.378244705882353, 0.3764705882352941, 0.3764705882352941, 0.3764705882352941, 0.37372549019607837, 0.3715294117647058, 0.36305882352941177, 0.36305882352941177, 0.34752941176470586, 0.34752941176470586, 0.32619607843137266, 0.28823529411764703, 0.3629537254901961, 0.28729411764705876, 0.3219607843137253, 0.34807843137254896, 0.3532282352941177, 0.3588235294117647, 0.360313725490196, 0.34752941176470586, 0.34752941176470586, 0.35043137254901957, 0.35043137254901957, 0.35890

In [24]:
s333

[([0.28670588235294,
   0.24020862745098076,
   0.27239215686274526,
   0.2837647058823531,
   0.28917647058823537,
   0.28988235294117637,
   0.29105882352941176,
   0.291185882352941,
   0.2978211764705885,
   0.32227921568627466,
   0.3431294117647061,
   0.35811764705882365,
   0.3635623529411767,
   0.3805819607843137,
   0.37827450980392163,
   0.38217254901960784,
   0.38125490196078426,
   0.3829066666666666,
   0.3803921568627451,
   0.3803921568627451,
   0.3803921568627451,
   0.3803921568627451,
   0.3803921568627451,
   0.3803921568627451,
   0.3785882352941176,
   0.378244705882353,
   0.3764705882352941,
   0.3764705882352941,
   0.3764705882352941,
   0.37372549019607837,
   0.3715294117647058,
   0.36305882352941177,
   0.36305882352941177,
   0.34752941176470586,
   0.34752941176470586,
   0.32619607843137266,
   0.28823529411764703,
   0.3629537254901961,
   0.28729411764705876,
   0.3219607843137253,
   0.34807843137254896,
   0.3532282352941177,
   0.35882352941176

In [25]:
s3333=[]
for (a,b) in s333:
    for i in a:
        s3333.append(i)

In [26]:
s3333

[0.28670588235294,
 0.24020862745098076,
 0.27239215686274526,
 0.2837647058823531,
 0.28917647058823537,
 0.28988235294117637,
 0.29105882352941176,
 0.291185882352941,
 0.2978211764705885,
 0.32227921568627466,
 0.3431294117647061,
 0.35811764705882365,
 0.3635623529411767,
 0.3805819607843137,
 0.37827450980392163,
 0.38217254901960784,
 0.38125490196078426,
 0.3829066666666666,
 0.3803921568627451,
 0.3803921568627451,
 0.3803921568627451,
 0.3803921568627451,
 0.3803921568627451,
 0.3803921568627451,
 0.3785882352941176,
 0.378244705882353,
 0.3764705882352941,
 0.3764705882352941,
 0.3764705882352941,
 0.37372549019607837,
 0.3715294117647058,
 0.36305882352941177,
 0.36305882352941177,
 0.34752941176470586,
 0.34752941176470586,
 0.32619607843137266,
 0.28823529411764703,
 0.3629537254901961,
 0.28729411764705876,
 0.3219607843137253,
 0.34807843137254896,
 0.3532282352941177,
 0.3588235294117647,
 0.360313725490196,
 0.34752941176470586,
 0.34752941176470586,
 0.350431372549019

In [27]:
for (a,b) in s333:
    a1=enumerate(a)
    print(list(a1))

[(0, 0.28670588235294), (1, 0.24020862745098076), (2, 0.27239215686274526), (3, 0.2837647058823531), (4, 0.28917647058823537), (5, 0.28988235294117637), (6, 0.29105882352941176), (7, 0.291185882352941), (8, 0.2978211764705885), (9, 0.32227921568627466), (10, 0.3431294117647061), (11, 0.35811764705882365), (12, 0.3635623529411767), (13, 0.3805819607843137), (14, 0.37827450980392163), (15, 0.38217254901960784), (16, 0.38125490196078426), (17, 0.3829066666666666), (18, 0.3803921568627451), (19, 0.3803921568627451), (20, 0.3803921568627451), (21, 0.3803921568627451), (22, 0.3803921568627451), (23, 0.3803921568627451), (24, 0.3785882352941176), (25, 0.378244705882353), (26, 0.3764705882352941), (27, 0.3764705882352941), (28, 0.3764705882352941), (29, 0.37372549019607837), (30, 0.3715294117647058), (31, 0.36305882352941177), (32, 0.36305882352941177), (33, 0.34752941176470586), (34, 0.34752941176470586), (35, 0.32619607843137266), (36, 0.28823529411764703), (37, 0.3629537254901961), (38, 0.2

In [28]:
for (a,b) in s444:
    a2=enumerate(a)
    print(list(a2))

[(0, 0.5263529411764705), (1, 0.5218619607843138), (2, 0.5177333333333333), (3, 0.5141223529411765), (4, 0.5020564705882354), (5, 0.4961270588235293), (6, 0.5026305882352943), (7, 0.5318901960784319), (8, 0.5677647058823533), (9, 0.580390588235294), (10, 0.543450980392156), (11, 0.4432423529411754), (12, 0.3852549019607845), (13, 0.388713725490196), (14, 0.38431372549019605), (15, 0.38431372549019605), (16, 0.38431372549019605), (17, 0.38431372549019605), (18, 0.38431372549019605), (19, 0.38580392156862753), (20, 0.38560470588235296), (21, 0.39333333333333326), (22, 0.3921568627450981), (23, 0.3921568627450981), (24, 0.3921568627450981), (25, 0.3921568627450981), (26, 0.3903388235294117), (27, 0.395607843137255), (28, 0.3941176470588236), (29, 0.39712470588235294), (30, 0.4), (31, 0.4), (32, 0.4001552941176471), (33, 0.3941960784313725), (34, 0.3977254901960785), (35, 0.3853160784313724), (36, 0.396078431372549), (37, 0.3943529411764705), (38, 0.3869019607843138), (39, 0.40239843137254

In [29]:
s444

[([0.5263529411764705,
   0.5218619607843138,
   0.5177333333333333,
   0.5141223529411765,
   0.5020564705882354,
   0.4961270588235293,
   0.5026305882352943,
   0.5318901960784319,
   0.5677647058823533,
   0.580390588235294,
   0.543450980392156,
   0.4432423529411754,
   0.3852549019607845,
   0.388713725490196,
   0.38431372549019605,
   0.38431372549019605,
   0.38431372549019605,
   0.38431372549019605,
   0.38431372549019605,
   0.38580392156862753,
   0.38560470588235296,
   0.39333333333333326,
   0.3921568627450981,
   0.3921568627450981,
   0.3921568627450981,
   0.3921568627450981,
   0.3903388235294117,
   0.395607843137255,
   0.3941176470588236,
   0.39712470588235294,
   0.4,
   0.4,
   0.4001552941176471,
   0.3941960784313725,
   0.3977254901960785,
   0.3853160784313724,
   0.396078431372549,
   0.3943529411764705,
   0.3869019607843138,
   0.40239843137254877,
   0.38431372549019605,
   0.38431372549019605,
   0.38431372549019605,
   0.38431372549019605,
   0.3843

In [30]:
s4444=[]
for (a,b) in s444:
    for i in a:
        s4444.append(i)

In [31]:
s4444

[0.5263529411764705,
 0.5218619607843138,
 0.5177333333333333,
 0.5141223529411765,
 0.5020564705882354,
 0.4961270588235293,
 0.5026305882352943,
 0.5318901960784319,
 0.5677647058823533,
 0.580390588235294,
 0.543450980392156,
 0.4432423529411754,
 0.3852549019607845,
 0.388713725490196,
 0.38431372549019605,
 0.38431372549019605,
 0.38431372549019605,
 0.38431372549019605,
 0.38431372549019605,
 0.38580392156862753,
 0.38560470588235296,
 0.39333333333333326,
 0.3921568627450981,
 0.3921568627450981,
 0.3921568627450981,
 0.3921568627450981,
 0.3903388235294117,
 0.395607843137255,
 0.3941176470588236,
 0.39712470588235294,
 0.4,
 0.4,
 0.4001552941176471,
 0.3941960784313725,
 0.3977254901960785,
 0.3853160784313724,
 0.396078431372549,
 0.3943529411764705,
 0.3869019607843138,
 0.40239843137254877,
 0.38431372549019605,
 0.38431372549019605,
 0.38431372549019605,
 0.38431372549019605,
 0.38431372549019605,
 0.3850980392156862,
 0.4472298039215688,
 0.5046274509803923,
 0.533333333

In [32]:
for x,y  in enumerate(data):
    for (a,b) in s333:
        for i in a:
            if y==i:
                data[x]=b
            else:
                pass
                
            

In [33]:
data

[0.5263529411764705,
 0.5218619607843138,
 0.5177333333333333,
 0.5141223529411765,
 0.5020564705882354,
 0.4961270588235293,
 0.5026305882352943,
 0.5318901960784319,
 0.5677647058823533,
 0.580390588235294,
 0.543450980392156,
 0.4432423529411754,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.3852549019607845,
 0.388713725490196,
 0.244,
 0.38431372549019605,
 0.38580392156862753,
 0.38560470588235296,
 0.39333333333333326,
 0.3921568627450981,
 0.3921568627450981,
 0.3903388235294117,
 0.395607843137255,
 0.3941176470588236,
 0.39712470588235294,
 0.4,
 0.4001552941176471,
 0.3941960784313725,
 0.244,
 0.244,
 0.3977254901960785,
 0.3853160784313724,
 0.244,
 0.396078431372549,
 0.3943529411764705,
 0.3869019607843138,
 0.40239843137254877,
 0.244,
 0.38431372549019605,
 0.244,
 0.3850980392156862,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.4472298039215688,
 0.5046274509803923,
 0.5

In [34]:
for x,y  in enumerate(data):
    for (a,b) in s444:
        for i in a:
            if y==i:
                data[x]=b
            else:
                pass

In [35]:
data

[0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.522,
 0.522,
 0.244,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.244,
 0.244,
 0.522,
 0.522,
 0.244,
 0.522,
 0.522,
 0.522,
 0.522,
 0.244,
 0.522,
 0.244,
 0.522,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,


In [36]:
data_1=data

In [37]:
data_1

[0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.522,
 0.522,
 0.244,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.244,
 0.244,
 0.522,
 0.522,
 0.244,
 0.522,
 0.522,
 0.522,
 0.522,
 0.244,
 0.522,
 0.244,
 0.522,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.522,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,
 0.244,


In [38]:
data_2=np.array(data_1)

In [39]:
data_2

array([0.522, 0.522, 0.522, ..., 0.244, 0.244, 0.244])

In [41]:
np.size(data_2)

10000

In [42]:
im_4=data_2.reshape((im_3.shape))

In [43]:
im_4

array([[0.522, 0.522, 0.522, ..., 0.244, 0.522, 0.522],
       [0.522, 0.522, 0.522, ..., 0.244, 0.244, 0.244],
       [0.522, 0.522, 0.522, ..., 0.244, 0.244, 0.244],
       ...,
       [0.244, 0.244, 0.244, ..., 0.244, 0.244, 0.244],
       [0.244, 0.244, 0.244, ..., 0.244, 0.244, 0.244],
       [0.244, 0.244, 0.244, ..., 0.244, 0.244, 0.244]])

In [48]:
cv2.imshow('im_4',im_4)

In [50]:
#cv2.waitKey(0)